# Cursor
env = XCURSOR_SIZE,18
env = HYPRCURSOR_SIZE,16
env = XCURSOR_PATH,$HOME/.icons:/usr/share/icons
env = XCURSOR_THEME,McMojave-cursors

# Cursor stability (optional – keep if no glitches)
env = WLR_NO_HARDWARE_CURSORS,1

# Wayland identity
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto

#theme
env = QT_QPA_PLATFORMTHEME,qt6ct

#Hyprland render
env = WLR_RENDERER,vulkan

# -------------------------
# AMD iGPU (PRIMARY)
# -------------------------
env = vblank_mode,0

# Mesa / OpenGL
env = mesa_glthread,true
env = amd_pstate,active
env = fps_max 60


# Vulkan
en = VKD3D_CONFIG,no_upload_hvv


#Hyprshot
env = HYPRSHOT_DIR,/home/pavan/Pictures


#nvidia
env = __GL_THREADED_OPTIMIZATIONS,0
env = NVD_BACKEND,direct
#env = GBM_BACKEND,nvidia-drm
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,0
env = __GL_MaxFramesAllowed,1
env = __GL_YIELD,USLEEP
env = NVreg_DynamicPowerManagement,0x02
env = __GL_SYNC_TO_VBLANK,0
