#Hyprshot
env = HYPRSHOT_DIR,/home/pavan/Pictures

#Cursor
env = XCURSOR_SIZE,18
env = HYPRCURSOR_SIZE,18
env = XCURSOR_PATH,$HOME/.icons:/usr/share/icons
env = XCURSOR_THEME,McMojave-cursors

#Wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

#Electron app fix
env = ELECTRON_OZONE_PLATFORM_HINT,auto

#Xdg
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

#Qt
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct

#Nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = __GL_VRR_ALLOWED,0

#Gpu
#env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1

#increasing shadere cache
env = export __GL_SHADER_DISK_CACHE,1
env = export __GL_SHADER_DISK_CACHE_SIZE,10737418240  
env = export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP,1