# Cursor
env = XCURSOR_SIZE,18
env = HYPRCURSOR_SIZE,16
env = XCURSOR_PATH,$HOME/.icons:/usr/share/icons
env = XCURSOR_THEME,McMojave-cursors



# Wayland identity
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = CLUTTER_BACKEND,wayland

#Electron / Chromium apps
env = ELECTRON_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1

#theme
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct

#Hyprland render


#Gpu order
env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1




# Vulkan
env = VKD3D_CONFIG,no_upload_hvv


#Hyprshot
env = HYPRSHOT_DIR,/home/pavan/Pictures


#nvidia
env = __GL_THREADED_OPTIMIZATIONS,1
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,0
env = __GL_MaxFramesAllowed,1
env = __GL_YIELD,USLEEP
env = LIBVA_DRIVER_NAME,radeonsi
env = __GL_GSYNC_ALLOWED,0
