general {
    gaps_in = 4
    gaps_out = 4

    border_size = 2
    

    col.active_border = rgba(248,248,248,0.56)
    col.inactive_border = rgba(59,51,55,1)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    allow_tearing = true

    layout = dwindle

    resize_on_border = false
    extend_border_grab_area = 15



}

decoration {
    rounding = 12
    rounding_power = 8

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    #inactive_opacity = 0.9

    #dim_inactive = true
    #dim_strength = 0.3

    shadow {
        enabled = false
        range = 42
        render_power = 4
        color = rgb(000000)
        scale = 1
    }

    blur {
        enabled = false
        size = 3
        passes = 1
        new_optimizations = true
        xray = false
    }
}



# -----------------------------------------------------
# Animation engine
# -----------------------------------------------------
animations {
    enabled = yes

    bezier = Global, 0.35,0.6,0.13,0.95
    bezier = Popsup, 0.25, 0.8, 0.25, 1
    bezier = Popsout, 0.25, 0.8, 0.25, 1
    bezier = Moves, 0.19, 1, 0.22, 1
    bezier = Workspace, 0.25, 0.8, 0.25, 1
    bezier = easeOut, 0.25, 0.9, 0.3, 1.0
    bezier = easeInOut, 0.42, 0.0, 0.58, 1.0
    bezier = overshot, 0.34, 1.56, 0.64, 1.0
    bezier = fastPremium, 0.05, 0.9, 0.1, 1.05
    bezier = instant, 0.3, 0, 0.1, 1
    bezier = premiumSmooth, 0.33, 1, 0.68, 1




    animation = windows, 1, 5, premiumSmooth, slide
    animation = windowsIn, 1, 5, premiumSmooth, slide 
    animation = windowsOut, 1, 5, premiumSmooth, slide
    animation = windowsMove, 1, 5, premiumSmooth
    animation = fade, 1, 5, premiumSmooth
    animation = fadeIn, 1, 5, premiumSmooth
    animation = fadeOut, 1, 5, premiumSmooth  
    animation = workspaces, 1, 5, premiumSmooth, slide
    animation = border, 1, 5, premiumSmooth
    animation = borderangle, 1, 5, premiumSmooth, loop


}


# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }


dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}


master {
    new_status = master
}


misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    disable_autoreload = false

}



vfr = false
vrr = 0

#layer rules
layerrule = animation slide, match:namespace rofi



