general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(255,255,255,0.5)
    col.inactive_border = rgba(76,57,57,0.32)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false
    allow_tearing = true
    layout = scrolling
    resize_on_border = false
    extend_border_grab_area = 15



}

decoration {
    rounding = 6
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.9

    #dim_inactive = true
    #dim_strength = 0.3

    shadow {
        enabled = false
        range = 42
        render_power = 4
        color = rgb(000000)
        scale = 1
    }

    blur {
        enabled = true
        size = 11
        passes = 3
        new_optimizations = true
        xray = false
    }
}



# -----------------------------------------------------
# Animation engine
# -----------------------------------------------------

animations {
    enabled = true

    bezier = windowsin, 0.51,0.36,0.47,0.91
    bezier = workspace, 0.24,0.65,0.47,0.98
    bezier = windowsout, 0.83,0.26,0,0.98
    bezier = windows, 0.7,0.42,0,0.99

    animation = windows, 1, 7, windows, slide
    animation = windowsIn, 1, 6, windowsin, popin 40%
    animation = windowsOut, 1, 7, windowsout, slidefade
    
    animation = workspaces, 1, 7, workspace, slide
    
    animation = fade, 1, 7, windows
    animation = border, 1, 7, windows
}


# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }


dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}


master {
    new_status = master
}


misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    disable_autoreload = false
    vfr = true
}

opengl {
    nvidia_anti_flicker = true
}

render {
   new_render_scheduling = false
   direct_scanout = true
}

cursor {
    sync_gsettings_theme = true
    no_hardware_cursors = 1
      
}

#layer rules
layerrule = animation slide, match:namespace rofi
layerrule = blur on, match:namespace rofi
layerrule = blur on, match:namespace swaync
layerrule = dim_around on, match:namespace rofi
layerrule = ignore_alpha a, match:namespace rofi
#layerrule = blur on, match:namespace waybar

#Tearing for games
#windowrule = match:class overwatch, immediate yes



